spring:
  application:
    name: msa-weather-proxy-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    city:
      path: /city/**
      serviceId: msa-weather-city-server
    data:
      path: /data/**
      serviceId: msa-weather-data-server
server:
  port: 8081