spring:
  application:
    name: msa-weather-data-server
  redis:
    host: 192.168.119.163
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084